import React from "react";
import {
  Home,
  BookOpen,
  CheckCircle,
  AlertCircle,
  ArrowLeftRight,
  Scissors,
  RotateCw,
  Footprints,
  Flower2,
  Shirt,
  Crown,
  User,
  Heart,
  Rabbit,
  CircleDot,
  AlertTriangle,
  Check,
  Stethoscope,
  Leaf,
  Camera,
  FileText,
  Plug,
  Droplets,
  Map,
  Sunrise,
  Sun,
  CloudSun,
  Sunset,
  Moon,
  Star,
  Sparkles,
  Search,
  Menu,
  X,
  HelpCircle,
  MapPin,
  Hotel,
  LifeBuoy,
  ClipboardList,
  Ban,
  Scale,
  Briefcase,
  Columns,
  RefreshCw,
  UserCheck,
  Phone,
  Contact,
  Info,
  ChevronLeft,
  ChevronRight,
  AlertOctagon,
} from "lucide-react";

export const IconMap = {
  home: Home,
  guide: BookOpen,
  recommended: CheckCircle,
  disliked: AlertCircle,
  mistakes: ArrowLeftRight,
  scissors: Scissors,
  tawaf: RotateCw,
  sai: Footprints,
  perfume: Flower2,
  clothing: Shirt,
  headcover: Crown,
  veil: User,
  marriage: Heart,
  hunting: Rabbit,
  circleDot: CircleDot,
  alert: AlertTriangle,
  check: Check,
  health: Stethoscope,
  spirituality: Leaf,
  camera: Camera,
  document: FileText,
  tech: Plug,
  soap: Droplets,
  map: Map,
  fajr: Sunrise,
  dhuhr: Sun,
  asr: CloudSun,
  maghrib: Sunset,
  isha: Moon,
  star: Star,
  sparkles: Sparkles,
  search: Search,
  menu: Menu,
  x: X,
  help: HelpCircle,
  mappin: MapPin,
  hotel: Hotel,
  lifebuoy: LifeBuoy,
  clipboard: ClipboardList,
  ban: Ban,
  scale: Scale,
  briefcase: Briefcase,
  columns: Columns,
  refresh: RefreshCw,
  usercheck: UserCheck,
  phone: Phone,
  contact: Contact,
  info: Info,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  alertOctagon: AlertOctagon,
} as const;

export type IconType = keyof typeof IconMap;

interface LucideIconProps extends React.ComponentPropsWithoutRef<"svg"> {
  name: string;
  className?: string;
  size?: number;
}

export function LucideIcon({ name, size = 20, className, ...props }: LucideIconProps) {
  // Convert emojis or descriptive strings to clean keys
  const cleanKey = (name || "").toLowerCase().trim();

  // Direct emoji mapping to ensure fallback compatibility
  const emojiToKeyMap: Record<string, IconType> = {
    "🏠": "home",
    "🕋": "columns", // Kaaba matches Columns structure
    "🏛️": "columns",
    "📋": "clipboard",
    "🚫": "ban",
    "⚖️": "scale",
    "⚠️": "alert",
    "🤲": "spirituality",
    "🧳": "briefcase",
    "🕌": "mappin",
    "🏨": "hotel",
    "🆘": "lifebuoy",
    "✂️": "scissors",
    "🌀": "tawaf",
    "🏃": "sai",
    "💅": "scissors",
    "🌹": "perfume",
    "👔": "clothing",
    "🧢": "headcover",
    "🧕": "veil",
    "💍": "marriage",
    "🔴": "ban",
    "🦌": "hunting",
    "🩺": "health",
    "🌿": "spirituality",
    "📷": "camera",
    "📄": "document",
    "🔌": "tech",
    "🧼": "soap",
    "🗺️": "map",
    "🌅": "fajr",
    "☀️": "dhuhr",
    "🌤️": "asr",
    "🌇": "maghrib",
    "🌙": "isha",
    "✅": "check",
    "📖": "guide",
    "💡": "info",
    ℹ️: "info",
    "❓": "help",
    "❔": "help",
    "؟": "help",
    "★": "star",
    "✨": "sparkles",
    "🪪": "document",
    "🚨": "alertOctagon",
    "📞": "phone",
    "📍": "mappin",
    "🕸️": "map",
    "🤝": "usercheck",
    "🎒": "briefcase",
  };

  const resolvedKey = emojiToKeyMap[cleanKey] || (cleanKey as IconType);
  const IconComponent = IconMap[resolvedKey] || HelpCircle;

  return <IconComponent size={size} className={className} {...props} />;
}
