/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WajibaatRouteImport } from './routes/wajibaat'
import { Route as UmrahRouteImport } from './routes/umrah'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as ProhibitionsRouteImport } from './routes/prohibitions'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as FidyaRouteImport } from './routes/fidya'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as ArkaanRouteImport } from './routes/arkaan'
import { Route as IndexRouteImport } from './routes/index'

const WajibaatRoute = WajibaatRouteImport.update({
  id: '/wajibaat',
  path: '/wajibaat',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrahRoute = UmrahRouteImport.update({
  id: '/umrah',
  path: '/umrah',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const ProhibitionsRoute = ProhibitionsRouteImport.update({
  id: '/prohibitions',
  path: '/prohibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const FidyaRoute = FidyaRouteImport.update({
  id: '/fidya',
  path: '/fidya',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const ArkaanRoute = ArkaanRouteImport.update({
  id: '/arkaan',
  path: '/arkaan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arkaan': typeof ArkaanRoute
  '/attractions': typeof AttractionsRoute
  '/duas': typeof DuasRoute
  '/fidya': typeof FidyaRoute
  '/hotels': typeof HotelsRoute
  '/mistakes': typeof MistakesRoute
  '/prohibitions': typeof ProhibitionsRoute
  '/tips': typeof TipsRoute
  '/umrah': typeof UmrahRoute
  '/wajibaat': typeof WajibaatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arkaan': typeof ArkaanRoute
  '/attractions': typeof AttractionsRoute
  '/duas': typeof DuasRoute
  '/fidya': typeof FidyaRoute
  '/hotels': typeof HotelsRoute
  '/mistakes': typeof MistakesRoute
  '/prohibitions': typeof ProhibitionsRoute
  '/tips': typeof TipsRoute
  '/umrah': typeof UmrahRoute
  '/wajibaat': typeof WajibaatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arkaan': typeof ArkaanRoute
  '/attractions': typeof AttractionsRoute
  '/duas': typeof DuasRoute
  '/fidya': typeof FidyaRoute
  '/hotels': typeof HotelsRoute
  '/mistakes': typeof MistakesRoute
  '/prohibitions': typeof ProhibitionsRoute
  '/tips': typeof TipsRoute
  '/umrah': typeof UmrahRoute
  '/wajibaat': typeof WajibaatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arkaan'
    | '/attractions'
    | '/duas'
    | '/fidya'
    | '/hotels'
    | '/mistakes'
    | '/prohibitions'
    | '/tips'
    | '/umrah'
    | '/wajibaat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arkaan'
    | '/attractions'
    | '/duas'
    | '/fidya'
    | '/hotels'
    | '/mistakes'
    | '/prohibitions'
    | '/tips'
    | '/umrah'
    | '/wajibaat'
  id:
    | '__root__'
    | '/'
    | '/arkaan'
    | '/attractions'
    | '/duas'
    | '/fidya'
    | '/hotels'
    | '/mistakes'
    | '/prohibitions'
    | '/tips'
    | '/umrah'
    | '/wajibaat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArkaanRoute: typeof ArkaanRoute
  AttractionsRoute: typeof AttractionsRoute
  DuasRoute: typeof DuasRoute
  FidyaRoute: typeof FidyaRoute
  HotelsRoute: typeof HotelsRoute
  MistakesRoute: typeof MistakesRoute
  ProhibitionsRoute: typeof ProhibitionsRoute
  TipsRoute: typeof TipsRoute
  UmrahRoute: typeof UmrahRoute
  WajibaatRoute: typeof WajibaatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wajibaat': {
      id: '/wajibaat'
      path: '/wajibaat'
      fullPath: '/wajibaat'
      preLoaderRoute: typeof WajibaatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umrah': {
      id: '/umrah'
      path: '/umrah'
      fullPath: '/umrah'
      preLoaderRoute: typeof UmrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prohibitions': {
      id: '/prohibitions'
      path: '/prohibitions'
      fullPath: '/prohibitions'
      preLoaderRoute: typeof ProhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidya': {
      id: '/fidya'
      path: '/fidya'
      fullPath: '/fidya'
      preLoaderRoute: typeof FidyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arkaan': {
      id: '/arkaan'
      path: '/arkaan'
      fullPath: '/arkaan'
      preLoaderRoute: typeof ArkaanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArkaanRoute: ArkaanRoute,
  AttractionsRoute: AttractionsRoute,
  DuasRoute: DuasRoute,
  FidyaRoute: FidyaRoute,
  HotelsRoute: HotelsRoute,
  MistakesRoute: MistakesRoute,
  ProhibitionsRoute: ProhibitionsRoute,
  TipsRoute: TipsRoute,
  UmrahRoute: UmrahRoute,
  WajibaatRoute: WajibaatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
